spring:
  application:
    name: ProLink

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 400000
      idle-timeout: 600000  # 10분
      connection-timeout: 30000 # 30초
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:

springdoc:
  swagger-ui:
    path: "/swagger-ui/index.html"
    operations-sorter: "alpha"
    tags-sorter: "alpha"
    disable-swagger-default-url: true
    # doc-expansion: "none"
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"

